on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: novotnyllc/test-action@v1.1
      with:
        who-to-greet: 'Adventurer'
